curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
curl -s  -L "http://localhost:3200/slow" > /dev/null &
curl -s  -L "http://localhost:3100/slow" > /dev/null &
