curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &
curl -vvv -L 'http://localhost:3100/slow/' &