{
 "title": "Load Shedding Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Non-Load Shedding Server: Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Client Response Time",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "NON_LS_client_time",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Request Handling Time",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "NON_LS_request_time",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Shedding Server: Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Client Response Time",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LS_client_time",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Request Handling Time",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LS_request_time",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Non Load Shedding Server: Number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of requests",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "NON_LS_request_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Shedding Server: Number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of requests",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LS_request_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}